// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Personal_Blog.Infra.SqlServer.EFCore.Persistence;

#nullable disable

namespace Personal_Blog.Infra.SqlServer.EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251128123524_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Personal_Blog.Domain.Core.Author.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ghazal@gmail.com",
                            FirstName = "غزل",
                            LastName = "مسیحا",
                            Password = "passGhazal",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "ghazal"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mina@gmail.com",
                            FirstName = "مینا",
                            LastName = "محمدی",
                            Password = "passMina",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "mina"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "reza@gmail.com",
                            FirstName = "رضا",
                            LastName = "رضایی",
                            Password = "passReza",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "reza"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara@gmail.com",
                            FirstName = "سارا",
                            LastName = "کاظمی",
                            Password = "passSara",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "sara"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hossein@gmail.com",
                            FirstName = "حسین",
                            LastName = "رضوانی",
                            Password = "passHossein",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Username = "hossein"
                        });
                });

            modelBuilder.Entity("Personal_Blog.Domain.Core.Category.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "تکنولوژی",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "سفر",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "سبک زندگی",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "برنامه‌نویسی .NET",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "کتاب و مطالعه",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "سلامت و ورزش",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Personal_Blog.Domain.Core.Comment.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("Comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "guest1@example.com",
                            FullName = "کاربر مهمان",
                            PostId = 1,
                            Rating = 5,
                            Status = "Confirmed",
                            Text = "خیلی ممنون، شروع خوبی برای پروژه بود!",
                            UpdatedAt = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maryam@example.com",
                            FullName = "مریم رضایی",
                            PostId = 1,
                            Rating = 4,
                            Status = "Pending",
                            Text = "مفید بود — لطفاً ادامه دهید.",
                            UpdatedAt = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hossein@example.com",
                            FullName = "حسین کریمی",
                            PostId = 2,
                            Rating = 5,
                            Status = "Confirmed",
                            Text = "مقاله عالی، خیلی کمک کرد.",
                            UpdatedAt = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "shakiba@example.com",
                            FullName = "شکیبا نوروزی",
                            PostId = 2,
                            Rating = 3,
                            Status = "Rejected",
                            Text = "خوبه ولی انتظار داشتم جزئیات فنی بیشتری باشه.",
                            UpdatedAt = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara@example.com",
                            FullName = "سارا رضوانی",
                            PostId = 3,
                            Rating = 5,
                            Status = "Confirmed",
                            Text = "چه خاطره خوبی!",
                            UpdatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "reza.abassi@example.com",
                            FullName = "رضا عباسی",
                            PostId = 3,
                            Rating = 4,
                            Status = "Pending",
                            Text = "دوست دارم وقتی سفر میکنم اینها رو بخونم.",
                            UpdatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ali.h@example.com",
                            FullName = "علی حسینی",
                            PostId = 4,
                            Rating = 5,
                            Status = "Confirmed",
                            Text = "مطالب زندگی سالم خیلی لازم بود، مرسی.",
                            UpdatedAt = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mina.k@example.com",
                            FullName = "مینا کریمی",
                            PostId = 4,
                            Rating = 4,
                            Status = "Pending",
                            Text = "لطفاً منابع هم معرفی کنید.",
                            UpdatedAt = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "booklover@example.com",
                            FullName = "کاربر عاشق کتاب",
                            PostId = 5,
                            Rating = 5,
                            Status = "Confirmed",
                            Text = "کتاب‌ها عالی هستند، لطفاً نقد هم بزنید.",
                            UpdatedAt = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "shahram@example.com",
                            FullName = "شهرام رضائی",
                            PostId = 5,
                            Rating = 3,
                            Status = "Pending",
                            Text = "کتاب‌ها آشنا نبودند، لطفاً منابع انگلیسی هم معرفی کنید.",
                            UpdatedAt = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maryam.n@example.com",
                            FullName = "مریم نعمتی",
                            PostId = 6,
                            Rating = 4,
                            Status = "Confirmed",
                            Text = "مفید بود، به نظرم ادامه این موضوع هم مهم است.",
                            UpdatedAt = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "traveller@example.com",
                            FullName = "مسافر مشتاق",
                            PostId = 8,
                            Rating = 5,
                            Status = "Confirmed",
                            Text = "مطلب خیلی مفید بود — امیدوارم به زودی سفر کنم!",
                            UpdatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "peace@example.com",
                            FullName = "کاربر آرامش",
                            PostId = 9,
                            Rating = 5,
                            Status = "Confirmed",
                            Text = "خیلی خوب — نیاز امروز بود.",
                            UpdatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "devnew@example.com",
                            FullName = "توسعه‌دهنده تازه‌کار",
                            PostId = 10,
                            Rating = 5,
                            Status = "Pending",
                            Text = "Blazor جالب است — آیا آموزش کامل دارید؟",
                            UpdatedAt = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Personal_Blog.Domain.Core.Post.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 3,
                            CategoryId = 4,
                            Content = "در این مقاله قصد داریم در قدم اول به چگونگی ایجاد یک پروژه ساده ASP.NET Core MVC بپردازیم. ابتدا باید SDK دات‌نت نصب شود، سپس یک پروژه جدید با دستور dotnet new mvc ساخته شود. پس از آن تنظیمات اتصال به دیتابیس و پیکربندی EF Core را انجام می‌دهیم. ادامه‌ی مطلب … (متن کامل را خودتان اضافه کنید)",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "شروع کار با ASP.NET Core MVC",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 3,
                            CategoryId = 4,
                            Content = "Entity Framework Core به ما این امکان را می‌دهد که مدل‌های C# را به جداول دیتابیس تبدیل کنیم. با مایگریشن، هر تغییر در مدل به‌صورت خودکار به دیتابیس اعمال می‌شود. در این نوشته درباره مزایا، معایب و نکات مهم EF Core بحث خواهیم کرد. ادامه‌ی مطلب …",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "معرفی EF Core و مایگریشن‌ها",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            CategoryId = 2,
                            Content = "شمال ایران با طبیعت بکر و آب‌وهوا دلپذیر همواره مقصد بسیاری از مسافران بوده است. در این نوشته تجربه من از سفری چندروزه به استان گیلان و مازندران آورده شده است: صبح زود از تهران حرکت کردیم … ادامه مطلب …",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "سفر به شمال ایران: تجربه‌ای متفاوت",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            CategoryId = 3,
                            Content = "داشتن سبک زندگی سالم نیازمند توجه به تغذیه، خواب، ورزش و آرامش ذهنی است. در این مقاله چند عادت ساده و عملی برای زندگی سالم پیشنهاد می‌شود: ۱) پیاده‌روی روزانه … ادامه مطلب …",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "سبک زندگی سالم — عادات روزمره",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 4,
                            CategoryId = 5,
                            Content = "خواندن کتاب یکی از بهترین روش‌ها برای بهبود مهارت‌های برنامه‌نویسی است. در این پست ۵ کتاب در حوزه دات‌نت و معماری نرم‌افزار معرفی می‌شود: ۱) Pro ASP.NET Core MVC … ادامه مطلب …",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "۵ کتاب عالی برای توسعه‌دهندگان .NET",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 5,
                            CategoryId = 6,
                            Content = "تغذیه مناسب و ورزش منظم به بدن انرژی می‌دهد و سلامت جسم و ذهن را تضمین می‌کند. در این مقاله نکاتی درباره رژیم غذایی، آب کافی و ورزش پیوسته گفته می‌شود … ادامه مطلب …",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "تغذیه سالم و ورزش روزانه",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 3,
                            CategoryId = 4,
                            Content = "پس از توسعه پروژه وب، زمان deploy و استقرار آن می‌رسد. در این مطلب گام‌های لازم برای deploy یک پروژه ASP.NET Core MVC روی سرور یا هاست بررسی شده است … ادامه مطلب …",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "چگونه پروژه MVC را deploy کنیم؟",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 1,
                            CategoryId = 2,
                            Content = "اگر قصد سفر به اروپا دارید، این راهنما برای شماست: مسافرت اقتصادی، انتخاب کشورها، زمان مناسب و نکات مهم … ادامه مطلب …",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "راهنمای سفر به اروپا",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 2,
                            CategoryId = 3,
                            Content = "زندگی پرشتاب امروزی استرس زیادی به ما تحمیل می‌کند. در این مقاله با مفهوم Mindfulness و تکنیک‌های کاهش استرس آشنا می‌شویم … ادامه مطلب …",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mindfulness و کاهش استرس",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 4,
                            CategoryId = 4,
                            Content = "Blazor چارچوب جدیدی برای ساخت رابط کاربری با C# و دات‌نت است. در این مطلب ابتدا با مفاهیم پایه آشنا می‌شویم … ادامه مطلب …",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "شروع یادگیری Blazor",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Personal_Blog.Domain.Core.Category.Entities.Category", b =>
                {
                    b.HasOne("Personal_Blog.Domain.Core.Author.Entities.Author", "Author")
                        .WithMany("Categories")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Personal_Blog.Domain.Core.Comment.Entities.Comment", b =>
                {
                    b.HasOne("Personal_Blog.Domain.Core.Post.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Personal_Blog.Domain.Core.Post.Entities.Post", b =>
                {
                    b.HasOne("Personal_Blog.Domain.Core.Author.Entities.Author", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Personal_Blog.Domain.Core.Category.Entities.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Personal_Blog.Domain.Core.Author.Entities.Author", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Personal_Blog.Domain.Core.Category.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Personal_Blog.Domain.Core.Post.Entities.Post", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
